# Generated by Django 4.2.7 on 2023-11-21 09:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('tin', models.IntegerField()),
                ('rs', models.CharField(max_length=20)),
                ('bic', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('login_time', models.DateTimeField(auto_now=True)),
                ('successful', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(default='', max_length=30)),
                ('service_status', models.CharField(max_length=20)),
                ('order_completion_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('service', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('lastLogin', models.DateField()),
                ('role', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UtilizerOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_received_at', models.DateTimeField(auto_now_add=True)),
                ('execution_time_seconds', models.IntegerField(default=0)),
                ('execution_completed_at', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('service_rendered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRendered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('performed_at', models.DateTimeField(auto_now=True)),
                ('completion_date', models.DateTimeField(null=True)),
                ('avg_deviation', models.FloatField(null=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('guid', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('ip', models.GenericIPAddressField()),
                ('social_sec_number', models.IntegerField(null=True)),
                ('ein', models.CharField(max_length=20, null=True)),
                ('social_type', models.CharField(max_length=10, null=True)),
                ('country', models.CharField(max_length=30)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('passport_series', models.IntegerField()),
                ('passport_number', models.IntegerField()),
                ('dob_timestamp', models.IntegerField()),
                ('insurance_name', models.CharField(max_length=30, null=True)),
                ('insurance_address', models.TextField(null=True)),
                ('insurance_inn', models.IntegerField(null=True)),
                ('insurance_policy', models.IntegerField(null=True)),
                ('insurance_bik', models.IntegerField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
