# Generated by Django 4.2.7 on 2023-11-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
