# Generated by Django 4.2.7 on 2023-11-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customers_country_alter_customers_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='dob_timestamp',
        ),
        migrations.AddField(
            model_name='customers',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
