# Generated by Django 4.2.7 on 2023-11-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customers_insurance_bik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='social_sec_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
