# Generated by Django 4.2.7 on 2023-11-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customers_insurance_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
