# Generated by Django 4.2.7 on 2023-11-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customers_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='dob',
        ),
        migrations.AddField(
            model_name='customers',
            name='dob_timestamp',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
