# Generated by Django 4.2.7 on 2023-11-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_customers_dob_customers_dob_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='services_offered',
            field=models.JSONField(null=True),
        ),
    ]
