# Generated by Django 4.2.7 on 2023-11-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_users_services_offered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='utilizeroperation',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='service_status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='services_offered',
            field=models.JSONField(),
        ),
    ]
