# Generated by Django 4.2.7 on 2023-11-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_completion_time',
            field=models.IntegerField(null=True),
        ),
    ]
