# Generated by Django 4.2.7 on 2023-11-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_order_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='lastLogin',
            new_name='last_login',
        ),
    ]
