# Generated by Django 4.2.7 on 2023-11-22 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_lastlogin_users_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerendered',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='utilizeroperation',
            name='execution_time_seconds',
        ),
        migrations.AddField(
            model_name='servicerendered',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='bic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='rs',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customers',
            name='ein',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='social_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
