# Generated by Django 4.2.7 on 2023-11-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_servicerendered_service_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='company_id',
        ),
        migrations.AddField(
            model_name='customers',
            name='company_name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
