# Generated by Django 4.2.7 on 2023-11-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_customers_company_id_customers_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
